### ISSUE TITLE
 Support conversion of Obsidian-style embedded images (![[image.png]]) to Markdown format for Quarto (![image.png](image.png))

### ISSUE THREAD

**Issue by machado-t** [MichelNivard/Ridian#2]
Embedded images in Obsidian format (`![[image.png]]`) aren't converted to the appropriate Markdown syntax (`![image.png](image.png)`), which causes missing images in the final .qmd file when rendered in Quarto.

Requested Feature:

It would be helpful if the plugin could recognize and convert Obsidian-style image embeds into standard Markdown image links, either by default or as an optional setting. This feature would streamline the process of converting notes with embedded media for Quarto presentation.

**Comment by MichelNivard** [comment]
Sounds very reasonable, it’ll be in the next update should be available in the coming week.
